languageCode = "en-us"
title = "Compromised Running - Hyrox, Resource for fitness Racing
description = "A resource for people looking to improve their functional fitness & racing"
enableRobotsTXT = true