languageCode = "en-us"
title = "Compromised Running"
description = "A resource for people looking to improve their functional fitness & racing"
enableRobotsTXT = true
disqusShortname = 'compromisedrunning'