baseurl = "/"
enableGitInfo = true
languageCode = "en-us"
languageLang = "en"
title = "Compromised Running"
description = "A resource for people looking to improve their functional fitness & racing"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableRobotsTXT = true
disqusShortname = 'compromisedrunning'
ignoreErrors = ["error-remote-getjson"]


[frontmatter]
  lastmod = [':git', 'last_updated', 'date']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[params.oembed]
  appId = "1271196743609704"
  privacy = false